every_day_parser:
  cron: '0 5 * * *'
  class: 'EveryDayParserJob'
  queue: 'data_mining'

event_parser:
  cron: '*/12 * * * *'
  class: 'EventParserJob'
  queue: 'data_mining'

token_reset:
  cron: '0 6 * * *'
  class: 'TokenResetJob'
  queue: 'default'

auth_accounts_check:
  cron: '5 6 * * *'
  class: 'AuthAccountsCheckJob'
  queue: 'default'

update_users_segment:
  cron: '0 0 * * *'
  class: 'BanditJobs::UserSegmentUpdateJob'
  queue: 'default'

weekly_reward_update:
  cron: '0 0 * * 0'
  class: 'BanditJobs::WeeklyRewardChangeJob'
  queue: 'default'