every_day_parser:
  cron: '0 5 * * *'
  class: 'EveryDayParserJob'
  queue: 'data_mining'

event_parser:
  cron: '*/12 * * * *'
  class: 'EventParserJob'
  queue: 'data_mining'

token_reset:
  cron: '0 6 * * *'
  class: 'TokenResetJob'
  queue: 'default'